[functions]
  directory = "api"
  included_files = ["wp/**"]
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
[template.environment]
  DATABASE = "wp-test"
  USERNAME = "ha4k276"
  PASSWORD = "4ujFqYWIdNG6"
  HOST = "ep-empty-voice-a21d4acy-pooler.eu-central-1.aws.neon.tech"
